# __________________________________ CONTENTS ___________________________________
#
#    This is a meta file for the 'mkdocs-awesome-nav' MkDocs plugin, it allows
#    us to manually specify navigation structure and order (by default the order
#    is alphabetic and sections correspond to directories).
# _______________________________________________________________________________

nav:
  - "Home": README.md
  - "Mod list": about/mod_table.md
  - "Asset list": about/resourcepack_table.md
  - "License": about/license.md

# Note: We use 'about/license.md' instead of the usual 'LICENSE.md' to work around the GitHub 
#       license detection quirks. The system requires license to be placed in root, while the 
#       website needs a copy in 'docs/'. If 'LICENSE.md' is located in both places GitHub tends
#       to randomly get confused and show two identical licenses when viewing the repo.
